if(0<$(".footer").find(".footer-country-selector").length){var FooterCountrySelectorModule=function(){function d(){var b=c.attr("data-last-country-label");c.append('\x3cspan class\x3d"sr-only"\x3e'+b+"\x3c/span\x3e")}var a=$(".footer").find(".footer-country-selector"),f=a.find(".footer-country-selector__country-select"),c=a.find(".footer-country-selector__country-list");return{init:function(){d();$("body").on("click touchstart",function(b){0==$(b.target).closest(".footer-country-selector").length&&
(c.slideUp(400),$(".footer-country-selector__country-select").get(0).setAttribute("aria-expanded",!1))});$(".footer-country-selector__country-group").keyup(function(b){"Escape"!==b.key&&27!==b.keyCode||$(".footer-country-selector__country-select").focus()});$(document).keyup(function(b){"Escape"!==b.key&&27!==b.keyCode||$(".footer-country-selector__country-select").click()});f.on("click keyup keydown",function(b){"keydown"==b.type?13==b.which&&(1==c.is(":visible")?(c.slideUp(400),$(".footer-country-selector__country-select").get(0).setAttribute("aria-expanded",
!1)):(c.slideDown(400),$(".footer-country-selector__country-select").get(0).setAttribute("aria-expanded",!0))):"click"==b.type&&(1!=c.is(":visible")?(c.slideDown(400),$(".footer-country-selector__country-select").get(0).setAttribute("aria-expanded",!0)):(c.slideUp(400),$(".footer-country-selector__country-select").get(0).setAttribute("aria-expanded",!1)))});c.find(".footer-country-selector__country-group:last-of-type").on("keydown",function(b){9==b.which&&1==c.is(":visible")&&(c.slideUp(400),$(".footer-country-selector__country-select").get(0).setAttribute("aria-expanded",
!1))});$(".footer-country-selector__country-group").each(function(b,c){$(this).attr("data-index",b+1)});$(".footer-country-selector__country-group").keydown(function(b){if(40==b.keyCode){var c=parseInt($(this).attr("data-index"))+1;$(".footer-country-selector__country-group[data-index\x3d"+c+"]").focus()}38==b.keyCode&&(b=parseInt($(this).attr("data-index"))-1,$(".footer-country-selector__country-group[data-index\x3d"+b+"]").focus())});$(".footer-country-selector__country-select").keydown(function(b){40==
b.keyCode&&$(".footer-country-selector__country-group:first").focus()});c.find("a.footer-country-selector__country-group").each(function(b,a){var d,f={40:1,38:-1};$(a).attr({"data-option-number":b});$(a).on("keydown",function(a){if(40==a.which||38==a.which){a.preventDefault();a.stopPropagation();var e=f[a.which];a=c.find("a.footer-country-selector__country-group");var g=parseInt(b);e=parseInt(g)+parseInt(e);0>e&&(e=a.length-1);e>a.length-1&&(e=0);d=c.find("[data-option-number\x3d'"+e+"']");d.focus()}})})}}}();
FooterCountrySelectorModule.init()}if(0<$(".footer").find(".footer-info").length){var FooterInfoModule=function(){var d=$(".footer").find(".footer-info");return{init:function(){d.find("a").on("click",function(){var a=$(this).text().trim();AnalyticsModule.linkClick("","Global Footer - Info",a)})}}}();FooterInfoModule.init()}
if(0<$(".footer").find(".footer-primary-links").length){var FooterPrimaryLinksModule=function(){var d=$(".footer").find(".footer-primary-links"),a=d.find(".footer-primary-links__category-label");return{init:function(){$(window).on("load resize",function(){"mobile"===UtilityModule.getViewport()?(a.attr("tabindex",0),a.attr("role","button"),a.attr("aria-expanded",!1)):(a.removeAttr("tabindex"),a.removeAttr("role"),a.removeAttr("aria-expanded"))});a.on("click",function(a){if("mobile"===UtilityModule.getViewport()){a=
$(this).closest(".footer-primary-links__category");var c=$(this).siblings(".footer-primary-links__category-container"),b=$(this);!0!==c.is(":visible")?(c.slideDown(400),a.addClass("active"),b.attr("aria-expanded",!0)):(c.slideUp(400),a.removeClass("active"),b.attr("aria-expanded",!1))}}).on("keydown",function(a){var c=a.keyCode;if(13===c||32===c)a.preventDefault(),$(this)[0].click()});d.find("a").on("click",function(){var a=$(this).parents(".footer-primary-links__category").find("span").text(),c=
$(this).text().trim();AnalyticsModule.linkClick(a,"Global Footer - Primary Links",c)})}}}();FooterPrimaryLinksModule.init()}if(0<$(".footer").find(".footer-secondary-links").length){var FooterSecondaryLinksModule=function(){var d=$(".footer").find(".footer-secondary-links");return{init:function(){d.find("a").on("click",function(){var a=$(this).text().trim();AnalyticsModule.linkClick("","Global Footer - Secondary Links",a)})}}}();FooterSecondaryLinksModule.init()}
if(0<$(".footer").find(".footer-social-media").length){var FooterSocialMediaModule=function(){var d=$(".footer").find(".footer-social-media");return{init:function(){d.find("a").on("click",function(){AnalyticsModule.linkClick("","Global Footer",$(this).attr("title"))})}}}();FooterSocialMediaModule.init()};